return (function(...)
	local Z = {
		"\072\098\048\083\081\098\105\102\066\079\072\069\053\074\051\061",
		"\066\074\067\083\100\043\061\061",
		"\097\068\057\083\053\081\061\061",
		"\053\078\120\082\083\083\070\099\090\112\061\061",
		"\082\087\084\068\097\112\061\061",
		"\082\087\084\102\066\047\072\057\056\043\061\061",
		"\088\071\090\116\056\074\086\067\056\047\089\085\076\057\077\112\075\113\089\061",
		"\115\079\067\118\066\079\071\061",
		"\076\047\067\121\053\079\084\065",
		"\069\085\043\088\081\106\061\061",
		"\049\048\066\102\112\081\061\061",
		"\075\074\048\087\075\057\072\099\076\083\053\112\071\079\090\080\056\111\076\061",
		"\079\074\112\080\050\065\049\061",
		"\097\066\102\043\072\087\102\100\080\083\097\077\119\052\051\061",
		"\048\098\067\102\115\089\053\052\076\070\108\077\100\074\080\070",
		"\076\098\048\083\066\074\048\083\097\082\072\105\097\047\080\057",
		"\110\050\047\101\121\069\099\085",
		"\107\065\101\066\111\121\057\043\097\114\043\068\089\101\056\119",
		"\076\079\067\102\076\068\090\061",
		"\114\089\079\067\050\043\061\061",
		"\089\112\121\066\084\057\121\114\050\081\061\061",
		"\066\089\097\112\090\071\065\108\100\071\084\113\075\047\051\069\053\112\061\061",
		"\053\047\080\052\066\116\107\061",
		"\119\087\077\067\078\090\043\049\097\111\116\100\099\119\089\053\069\081\061\061",
		"\102\120\071\111\071\080\117\120",
		"\103\083\082\076\074\120\104\121\074\054\108\120\101\113\086\088",
		"\052\069\106\043\089\084\110\089\043\068\071\121",
		"\102\068\082\119\047\055\117\048\099\081\082\056\100\084\054\101\049\105\068\111\071\106\061\061",
		"\066\079\048\121",
		"\065\100\088\110\089\113\051\104\097\068\114\056\071\117\049\069",
		"\100\071\065\049\076\074\102\085\115\074\087\121\100\068\108\121\090\057\077\061",
		"\115\074\085\112\097\074\108\104",
		"\118\070\090\086\066\120\057\073",
		"\072\119\054\043\079\119\047\087\048\108\074\114\079\069\119\054\054\051\109\076\070\081\061\061",
		"\100\084\067\107\048\088\068\065\106\116\077\112\056\051\089\061",
		"\078\110\098\103\079\098\089\098",
		"\049\056\057\109\074\080\099\118\081\081\061\061",
		"\106\121\043\121\084\106\061\061",
		"\078\120\047\053\079\069\119\057\097\107\082\082\081\119\069\067",
		"\053\047\057\069\053\082\072\052\115\074\108\077\100\074\085\083\053\082\086\057\076\116\081\061",
		"\053\098\067\065\053\081\061\061",
		"\075\082\108\110",
		"\119\077\113\047\055\115\072\104",
		"\049\076\054\115\097\081\085\057\111\043\061\061",
		"\097\098\105\105\076\106\061\061",
		"\081\083\086\107\050\079\085\067\074\057\067\071\097\088\086\052",
		"\052\102\055\106\082\112\061\061",
		"\052\047\106\080\077\105\054\120",
		"\105\073\108\056\111\099\087\082\079\086\077\118",
		"\076\079\108\105\066\079\112\061",
		"\084\086\066\086\050\082\100\088",
		"\076\087\067\053",
		"\082\087\084\065\053\082\072\105\115\079\067\118\066\079\071\061",
		"\076\116\072\069\100\074\085\068",
		"\048\047\048\111\115\079\084\069\090\112\061\061",
		"\101\090\103\105\069\099\065\071\079\100\089\061",
		"\082\087\084\049\053\074\051\061",
		"\043\051\114\097\098\073\104\115\074\081\061\061",
		"\115\079\067\120\100\112\061\061",
		"\072\047\057\121\053\089\053\102\076\068\108\083\081\098\105\102\066\079\081\061",
		"\065\052\051\118\085\056\052\055",
		"\082\083\076\061",
		"\074\099\116\089\057\108\086\087\080\088\074\074\057\087\043\056\099\088\113\109\106\106\061\061",
		"\089\089\075\070\119\115\071\061",
		"\053\071\087\100\115\047\108\078\072\098\115\077\053\113\110\057",
		"\108\120\105\104\075\071\105\051\056\082\108\048\050\113\105\074\076\070\089\061",
		"\113\112\118\105\087\109\050\107\069\122\083\119",
		"",
		"\076\089\072\098\115\098\070\098\081\057\097\112\071\098\108\052",
		"\090\068\105\057\090\082\067\070\108\047\072\067\071\057\057\118\088\106\061\061",
		"\079\077\067\056\099\112\061\061",
		"\076\047\048\065\066\116\053\057",
		"\115\098\084\069\100\116\108\112\097\074\108\057",
		"\097\074\085\108\048\111\108\098\048\079\057\068\056\082\115\083\088\068\081\061",
		"\070\101\104\085\066\072\086\099\069\101\055\122\089\112\061\061",
		"\055\051\104\070\052\066\068\087",
		"\076\115\072\119\088\076\077\061",
		"\100\078\067\055\072\068\115\083\076\082\105\069\108\071\076\085\097\112\061\061",
		"\098\108\085\104\082\100\109\043",
	}
	for a, u in ipairs({ { 1, 79 }, { 1, 57 }, { 58, 79 } }) do
		while u[1] < u[2] do
			Z[u[1]], Z[u[2]], u[1], u[2] = Z[u[2]], Z[u[1]], u[1] + 1, u[2] - 1
		end
	end
	local function a(a)
		return Z[a + 39695]
	end
	do
		local a = Z
		local u = type
		local L = {
			a = 24,
			A = 45,
			["\043"] = 0,
			g = 42,
			S = 52,
			L = 28,
			["\051"] = 56,
			["\050"] = 14,
			m = 59,
			["\047"] = 38,
			F = 36,
			W = 53,
			B = 27,
			P = 49,
			z = 31,
			o = 35,
			n = 1,
			X = 19,
			y = 46,
			["\055"] = 10,
			x = 51,
			["\048"] = 21,
			["\052"] = 47,
			I = 2,
			p = 48,
			T = 61,
			b = 54,
			w = 11,
			V = 9,
			R = 23,
			u = 60,
			["\053"] = 25,
			N = 7,
			C = 5,
			Z = 12,
			s = 29,
			M = 40,
			E = 50,
			e = 62,
			H = 17,
			f = 41,
			["\049"] = 44,
			U = 57,
			t = 55,
			r = 58,
			d = 26,
			O = 6,
			j = 32,
			q = 3,
			["\056"] = 30,
			k = 8,
			h = 43,
			v = 34,
			l = 13,
			J = 22,
			i = 33,
			c = 15,
			["\057"] = 37,
			["\054"] = 63,
			Y = 4,
			K = 18,
			D = 39,
			Q = 16,
			G = 20,
		}
		local J = table.insert
		local T = string.len
		local k = table.concat
		local l = string.char
		local d = string.sub
		local F = math.floor
		for Z = 1, #a, 1 do
			local q = a[Z]
			if u(q) == "\115\116\114\105\110\103" then
				local u = T(q)
				local v = {}
				local A = 1
				local P = 0
				local N = 0
				while A <= u do
					local Z = d(q, A, A)
					local a = L[Z]
					if a then
						P = P + a * 64 ^ (3 - N)
						N = N + 1
						if N == 4 then
							N = 0
							local Z = F(P / 65536)
							local a = F((P % 65536) / 256)
							local u = P % 256
							J(v, l(Z, a, u))
							P = 0
						end
					elseif Z == "\061" then
						J(v, l(F(P / 65536)))
						if A >= u or d(q, A + 1, A + 1) ~= "\061" then
							J(v, l(F((P % 65536) / 256)))
						end
						break
					end
					A = A + 1
				end
				a[Z] = k(v)
			end
		end
	end
	return (function(Z, L, J, T, k, l, d, m, j, D, u, F, P, N, v, w, z, e, q, A, E)
		P, m, u, z, E, q, N, w, e, F, A, v, D, j =
			function(Z)
				for a = 1, #Z, 1 do
					q[Z[a]] = q[Z[a]] + 1
				end
				if J then
					local u = J(true)
					local L = k(u)
					L[a(-39632)], L[a(-39633)], L[a(-39660)] = Z, N, function()
						return 1653427
					end
					return u
				else
					return T({}, {
						[a(-39633)] = N,
						[a(-39632)] = Z,
						[a(-39660)] = function()
							return 1653427
						end,
					})
				end
			end, function(Z)
				q[Z] = q[Z] - 1
				if 0 == q[Z] then
					q[Z], F[Z] = nil, nil
				end
			end, function(u, J, T, k)
				local z, d, r, K, N, f, p, B, s, i, Q, S, q, g, x, P, R, U, W, H, o, X, h, A, O, n, Y, I, y, c, b
				while u do
					if u < 10674592 then
						if u < 5579515 then
							if u < 2710450 then
								if u < 1779930 then
									if u < 1213902 then
										if u < 1137244 then
											u = F[z]
											o = a(-39666)
											s = F[T[2]]
											X = 2566321529598
											x = F[T[3]]
											g = 252328
											B = X - g
											O = x(o, B)
											d = s[O]
											s = y + A
											u[d] = s
											u = 15834596
										else
											K, r = X(g, K)
											u = K and 13500316 or 15624157
										end
									else
										if u < 1592469 then
											u = F[z]
											X = 23729343719764
											s = F[T[2]]
											o = a(-39641)
											g = -1010943
											x = F[T[3]]
											B = X - g
											O = x(o, B)
											d = s[O]
											s = y
											u[d] = s
											u = 15834596
										else
											A = F[T[2]]
											N = -782067
											z = -782136
											P = N - z
											q = A * P
											P = 23290170188290
											N = -733879
											A = P - N
											P = 799161
											d = q + A
											A = 35184372887993
											q = A - P
											u = d % q
											F[T[2]] = u
											N = 782200
											P = 782201
											q = F[T[3]]
											u = 11135316
											A = P - N
											d = q ~= A
										end
									end
								else
									if u < 2355361 then
										if u < 2281342 then
											i = x
											U = a(-39663)
											r = Z[U]
											u = 7485156
											p = -146469
											U = a(-39635)
											K = r[U]
											r = K(q, i)
											K = F[T[6]]
											U = K()
											i = nil
											K = 105251
											f = -146468
											g = r + U
											r = -104995
											X = g + y
											g = K + r
											B = X % g
											g = P[A]
											U = f - p
											y = B
											r = y + U
											K = N[r]
											X = g .. K
											P[A] = X
										else
											q = J[1]
											A = J[2]
											u = F[T[1]]
											P = u
											u = P[A]
											u = u and 10546498 or 11001680
										end
									else
										if u < 2389125 then
											g = 671989
											d = F[q]
											X = 34237303569794
											s = F[T[2]]
											o = a(-39669)
											x = F[T[3]]
											B = X - g
											O = x(o, B)
											y = s[O]
											u = d[y]
											y = u
											u = A and 862746 or 1232933
										else
											r = a(-39678)
											p = -318570
											X = F[P]
											g = F[A]
											f = 3924645818845
											u = 7885553
											U = f - p
											K = g(r, U)
											g = 328042
											B = X[K]
											K = -328041
											U = a(-39637)
											X = g + K
											O[B] = X
											U = O[U]
											X = a(-39619)
											B = Z[X]
											r = { U(O) }
											U = { B(L(r)) }
											K = U[3]
											g = U[2]
											X = U[1]
										end
									end
								end
							else
								if u < 4058510 then
									if u < 3528505 then
										if u < 2747498 then
											u = O
											z = u
											x = nil
											O = nil
											o = nil
											u = 9113366
										else
											W = a(-39661)
											U = a(-39675)
											b = 21931845206414
											U = r[U]
											B = K
											p = F[P]
											h = F[A]
											S = -855611
											c = b - S
											R = h(W, c)
											f = p[R]
											U = U(r, f)
											u = U and 7426787 or 5216927
										end
									else
										if u < 3900599 then
											A = J[2]
											q = v()
											P = J[3]
											F[q] = J[1]
											d = F[q]
											u = not d
											u = u and 15247826 or 7340256
										else
											u = d and 8444162 or 2357320
										end
									end
								else
									if u < 5238589 then
										if u < 4482675 then
											Y = 1018432
											u = F[T[1]]
											N = a(-39638)
											q = F[T[2]]
											A = F[T[3]]
											y = 23908666106170
											z = y - Y
											P = A(N, z)
											d = q[P]
											q = F[T[4]]
											u[d] = q
											d = {}
											u = Z[a(-39671)]
										else
											B = nil
											u = 7885553
											r = nil
										end
									else
										u = 16461303
										Y = nil
										N = nil
										y = nil
									end
								end
							end
						else
							if u < 7862691 then
								if u < 7340134 then
									if u < 7039056 then
										if u < 6029585 then
											u = 13570974
										else
											s, O = Y(i, s)
											u = s and 12007279 or 9113366
										end
									else
										if u < 7268870 then
											U = X
											u = U
											B[U] = u
											u = 10342716
											U = nil
										else
											z = 782200
											N = 782201
											A = F[T[3]]
											P = N - z
											q = A ~= P
											u = q and 13226388 or 11135316
										end
									end
								else
									if u < 7453490 then
										if u < 7388293 then
											N = F[T[1]]
											u = N and 14272436 or 14182833
											d = N
										else
											f = F[P]
											R = a(-39642)
											p = F[A]
											c = 670389
											u = 5216927
											b = 30309434766222
											W = c + b
											h = p(R, W)
											U = f[h]
											f = false
											r[U] = f
										end
									else
										if u < 7653695 then
											x = x + O
											B = not o
											i = x <= s
											i = B and i
											B = x >= s
											B = o and B
											i = B or i
											B = 1794102
											u = i and B
											i = 5349027
											u = u or i
										else
											K = 413485
											g = -413485
											d = #B
											X = g + K
											u = d == X
											u = u and 12929419 or 14363063
										end
									end
								end
							else
								if u < 8931982 then
									if u < 8775021 then
										if u < 8036803 then
											K, r = X(g, K)
											u = K and 3211874 or 5834930
										else
											d = {}
											u = Z[a(-39647)]
										end
									else
										if u < 8875483 then
											P = a(-39630)
											u = Z[a(-39616)]
											A = Z[P]
											P = a(-39645)
											q = A[P]
											P = F[T[1]]
											A = { q(P) }
											d = { L(A) }
										else
											R = 139748
											f = a(-39618)
											h = 3052741307647
											g = a(-39658)
											u = 15686111
											X = Z[g]
											K = F[P]
											r = F[A]
											p = h - R
											U = r(f, p)
											g = K[U]
											B = X[g]
											X = B()
										end
									end
								else
									if u < 10394652 then
										if u < 9962172 then
											X = 381036
											s = F[P]
											x = F[A]
											o = a(-39624)
											r = -479087
											g = 6591901845391
											B = X + g
											Y = a(-39623)
											Y = z[Y]
											O = x(o, B)
											i = s[O]
											Y = Y(z, i)
											U = 8486041316501
											O = F[P]
											X = a(-39693)
											o = F[A]
											s = a(-39623)
											s = z[s]
											K = 5838111983054
											g = K - r
											r = -708022
											B = o(X, g)
											x = O[B]
											g = a(-39659)
											s = s(z, x)
											o = F[P]
											B = F[A]
											K = r + U
											X = B(g, K)
											O = o[X]
											K = -753847
											r = 3147234085930
											x = a(-39623)
											x = s[x]
											x = x(s, O)
											f = 12508401137789
											O = F[P]
											o = F[A]
											X = a(-39681)
											g = K + r
											B = o(X, g)
											r = 17657150218229
											K = -810937
											X = a(-39680)
											s = O[B]
											i = x[s]
											O = F[P]
											o = F[A]
											s = a(-39623)
											g = K + r
											r = a(-39634)
											B = o(X, g)
											x = O[B]
											s = z[s]
											s = s(z, x)
											x = nil
											X = F[P]
											g = F[A]
											p = 903932
											U = f - p
											u = 15686111
											K = g(r, U)
											r = a(-39628)
											o = a(-39623)
											o = z[o]
											p = -137892
											B = X[K]
											o = o(z, B)
											f = 4741788464796
											X = F[P]
											g = F[A]
											U = f - p
											K = g(r, U)
											B = X[K]
											O = o[B]
											o = j(3758706, { y, P, A })
										else
											U = not r
											X = X + K
											d = X <= g
											d = U and d
											U = X >= g
											U = r and U
											d = U or d
											U = 7168731
											u = d and U
											d = 13538717
											u = u or d
										end
									else
										u = 16461303
									end
								end
							end
						end
					else
						if u < 13527184 then
							if u < 12234520 then
								if u < 11639784 then
									if u < 11394722 then
										if u < 11009764 then
											x = 323819
											u = {}
											F[T[2]] = u
											d = F[T[3]]
											s = 848186
											y = 34465
											N = d
											Y = 35184372054367
											z = y + Y
											d = A % z
											F[T[4]] = d
											i = 848441
											Y = i - s
											i = -58594
											y = A % Y
											s = 58596
											Y = i + s
											z = y + Y
											F[T[5]] = z
											i = a(-39663)
											u = 7485156
											Y = Z[i]
											i = a(-39688)
											y = Y[i]
											Y = y(q)
											s = -320746
											y = a(-39649)
											P[A] = y
											i = -320610
											O = 691574
											y = i - s
											s = -323818
											o = 691573
											i = s + x
											s = Y
											x = O - o
											O = x
											x = 0
											o = O < x
											x = i - O
										else
											A = F[T[3]]
											z = 39663
											N = -39521
											P = N + z
											q = A * P
											u = 7339744
											P = 807162
											N = 806905
											A = P - N
											d = q % A
											F[T[3]] = d
										end
									else
										if u < 11468074 then
											p = 15403297020792
											X = F[P]
											f = -484207
											r = a(-39687)
											g = F[A]
											U = f + p
											K = g(r, U)
											g = 273001
											B = X[K]
											K = 273000
											X = g - K
											u = 8893711
											i[B] = X
										else
											z = a(-39674)
											d = F[T[1]]
											A = F[T[2]]
											i = -28641
											P = F[T[3]]
											Y = 8726566088670
											y = Y - i
											N = P(z, y)
											q = A[N]
											u = d[q]
											d = { u }
											u = Z[a(-39648)]
										end
									end
								else
									if u < 12027585 then
										if u < 11660561 then
											u = a(-39657)
											z = F[T[2]]
											x = 4265033370873
											O = 687477
											y = F[T[3]]
											u = N[u]
											s = x - O
											i = a(-39689)
											Y = y(i, s)
											d = z[Y]
											z = v()
											u = u(N, d)
											F[z] = u
											d = F[z]
											u = not d
											u = u and 16658429 or 13466523
										else
											x = s
											K = a(-39640)
											B = F[P]
											U = 904572
											f = 24032148261361
											u = a(-39623)
											X = F[A]
											u = O[u]
											r = U + f
											g = X(K, r)
											o = B[g]
											p = 28025516215615
											u = u(O, o)
											g = F[P]
											U = a(-39625)
											K = F[A]
											o = u
											h = -661685
											f = p - h
											r = K(U, f)
											X = g[r]
											B = o[X]
											X = F[y]
											u = B == X
											u = u and 2736723 or 12391290
										end
									else
										if u < 12127671 then
											A = 637236
											q = F[T[1]]
											d = #q
											P = 637236
											q = A - P
											u = d == q
											u = u and 1769014 or 8817933
										else
											s = F[i]
											u = 4019834
											y = not s
											d = y
										end
									end
								end
							else
								if u < 13071718 then
									if u < 12461789 then
										if u < 12369634 then
											X = a(-39619)
											U = a(-39637)
											B = Z[X]
											U = Y[U]
											r = { U(Y) }
											U = { B(L(r)) }
											u = 1169955
											K = U[3]
											g = U[2]
											X = U[1]
										else
											u = 6430916
											O = nil
											x = nil
											o = nil
										end
									else
										if u < 12891991 then
											u = Z[a(-39626)]
											d = {}
										else
											f = a(-39632)
											g = v()
											K = v()
											u = {}
											X = v()
											Y = nil
											F[X] = u
											u = E(12114802, { X, i, s, N })
											N = m(N)
											d = a(-39622)
											R = nil
											F[g] = u
											z = nil
											u = {}
											h = a(-39664)
											r = {}
											F[K] = u
											u = Z[d]
											p = F[K]
											U = { [f] = p, [h] = R }
											d = u(r, U)
											u = D(2347591, { K, X, O, i, s, g })
											F[P] = d
											y = nil
											g = m(g)
											N = a(-39644)
											x = nil
											K = m(K)
											X = m(X)
											B = nil
											g = 3066700383245
											i = m(i)
											s = m(s)
											O = m(O)
											s = a(-39673)
											o = nil
											F[A] = u
											X = -145637
											u = Z[N]
											N = a(-39623)
											o = -1030400
											y = F[P]
											N = u[N]
											O = 30965510682534
											Y = F[A]
											x = O - o
											i = Y(s, x)
											o = a(-39617)
											z = y[i]
											N = N(u, z)
											u = nil
											i = a(-39676)
											z = u
											Y = Z[i]
											s = F[P]
											x = F[A]
											B = X + g
											O = x(o, B)
											B = 29323709786555
											i = s[O]
											y = Y[i]
											X = -573682
											i = F[P]
											O = a(-39682)
											s = F[A]
											o = B - X
											x = s(O, o)
											Y = i[x]
											u = y[Y]
											Y = a(-39619)
											y = v()
											O = a(-39637)
											F[y] = u
											u = Z[Y]
											O = N[O]
											x = { O(N) }
											O = { u(L(x)) }
											u = 6430916
											s = O[3]
											Y = O[1]
											i = O[2]
										end
									end
								else
									if u < 13499692 then
										if u < 13247817 then
											A = F[T[3]]
											o = -387167
											z = 637812
											N = 637844
											K = -713622
											O = -264550
											P = N - z
											q = A % P
											N = F[T[4]]
											x = 264552
											g = 713654
											B = -387180
											Y = F[T[2]]
											s = x + O
											O = o - B
											X = F[T[3]]
											B = X - q
											X = g + K
											o = B / X
											x = O - o
											i = s ^ x
											y = Y / i
											Y = 4295924350
											z = N(y)
											x = 420205
											y = -957054
											N = y + Y
											y = -944573
											s = 420206
											Y = 944575
											P = z % N
											z = y + Y
											N = z ^ q
											A = P / N
											N = F[T[4]]
											i = s - x
											x = 4294714776
											Y = A % i
											q = nil
											s = 252520
											i = s + x
											y = Y * i
											z = N(y)
											Y = 144418
											N = F[T[4]]
											y = N(A)
											P = z + y
											A = nil
											y = -78882
											x = -127780
											i = 401578
											s = 336042
											z = y + Y
											N = P % z
											y = P - N
											Y = i - s
											z = y / Y
											u = 8817933
											O = -128036
											s = -568050
											i = 568306
											Y = i + s
											o = 847610
											B = -847354
											y = N % Y
											i = N - y
											s = x - O
											Y = i / s
											N = nil
											x = 9056
											O = 8800
											s = x - O
											i = z % s
											x = z - i
											O = o + B
											P = nil
											z = nil
											s = x / O
											x = { y, Y, i, s }
											s = nil
											i = nil
											F[T[1]] = x
											y = nil
											Y = nil
										else
											d = a(-39667)
											u = Z[d]
											Y = w(11612515, { z, T[2], T[3] })
											i = { u(Y) }
											d = i[1]
											Y = d
											y = i[2]
											i = v()
											F[i] = y
											y = not Y
											u = y and 4019834 or 12156275
											d = y
										end
									else
										b = 4636559654556
										c = -961982
										R = a(-39692)
										n = 912700
										f = F[P]
										B = K
										p = F[A]
										W = c + b
										h = p(R, W)
										U = f[h]
										H = a(-39650)
										B = nil
										R = F[y]
										Q = 8899442914084
										c = F[P]
										b = F[A]
										I = n + Q
										S = b(H, I)
										W = c[S]
										I = -197862
										h = R[W]
										S = a(-39683)
										W = F[P]
										c = F[A]
										n = 15866093584030
										H = I + n
										b = c(S, H)
										R = W[b]
										p = h[R]
										R = F[P]
										u = 1169955
										W = F[A]
										b = a(-39656)
										H = -193766
										I = 12450416599601
										S = H + I
										c = W(b, S)
										h = R[c]
										f = p[h]
										r[U] = f
										r = nil
									end
								end
							end
						else
							if u < 14829377 then
								if u < 14294350 then
									if u < 14041255 then
										if u < 13551872 then
											g = -413485
											d = #B
											K = 413485
											X = g + K
											u = d == X
											u = 14363063
										else
											g = a(-39658)
											R = 24811709914799
											h = -394348
											X = Z[g]
											f = a(-39627)
											K = F[P]
											r = F[A]
											p = h + R
											U = r(f, p)
											g = K[U]
											B = X[g]
											R = 12831606241738
											W = -144612
											K = a(-39662)
											g = 0.1
											X = B(g)
											g = Z[K]
											r = F[P]
											U = F[A]
											h = R - W
											p = a(-39665)
											f = U(p, h)
											p = 472943
											K = r[f]
											X = g[K]
											f = -9760
											r = -198630
											U = 198630
											K = r + U
											h = -331178
											U = -9755
											r = U - f
											R = 25315310135746
											f = 472943
											U = f - p
											g = X(K, r, U)
											X = 0.15
											B = o(i, g, X)
											f = a(-39691)
											K = F[P]
											r = F[A]
											p = h + R
											U = r(f, p)
											g = K[U]
											r = -301672
											K = 301673
											X = i[g]
											g = K + r
											B = X < g
											u = B and 11423069 or 8893711
										end
									else
										if u < 14258870 then
											N = d
											u = not N
											u = u and 12781958 or 11641187
										else
											z = F[T[1]]
											Y = F[T[2]]
											x = a(-39690)
											i = F[T[3]]
											o = -270376
											B = 15405444356147
											O = o + B
											s = i(x, O)
											y = Y[s]
											u = 14182833
											N = z[y]
											d = N
										end
									end
								else
									if u < 14602889 then
										if u < 14540609 then
											X = 733112
											g = 733111
											d = X - g
											f = 316139
											U = -316138
											X = #B
											u = z(d, X)
											X = u
											u = y(B, X)
											g = u
											u = F[O]
											r = U + f
											K = g - r
											d = Y(K)
											X = nil
											u[g] = d
											g = nil
											u = 7747308
										else
											N = -331498
											z = -331498
											d = a(-39677)
											u = Z[d]
											q = F[T[1]]
											A = F[T[2]]
											P = N - z
											d = u(q, A, P)
											q = a(-39658)
											d = Z[q]
											z = a(-39670)
											A = F[T[3]]
											P = F[T[4]]
											Y = 25551541133744
											i = 918716
											y = Y - i
											N = P(z, y)
											z = 513904
											q = A[N]
											u = d[q]
											q = 0.05
											d = u(q)
											d = a(-39677)
											u = Z[d]
											q = F[T[1]]
											N = 513905
											A = F[T[2]]
											P = N - z
											d = u(q, A, P)
											d = {}
											u = Z[a(-39652)]
										end
									else
										K = 565490
										s = 437678
										u = nil
										A = v()
										X = -1014974
										d = nil
										z = a(-39636)
										N = a(-39636)
										F[A] = u
										P = v()
										F[P] = d
										q = J
										d = Z[N]
										N = a(-39694)
										u = d[N]
										g = -1014975
										y = a(-39630)
										o = 269224
										N = v()
										F[N] = u
										d = Z[z]
										z = a(-39629)
										Y = a(-39663)
										u = d[z]
										d = Z[y]
										y = a(-39645)
										z = u
										u = d[y]
										d = Z[Y]
										Y = a(-39672)
										y = u
										u = d[Y]
										d = 995519
										i = -995519
										Y = u
										u = d + i
										r = 937534
										i = v()
										F[i] = u
										d = 437680
										u = d - s
										s = v()
										F[s] = u
										u = {}
										O = v()
										d = 269224
										x = u
										u = {}
										F[O] = u
										u = d - o
										o = u
										u = {}
										d = X - g
										g = -565234
										B = u
										X = g + K
										u = 10342716
										g = X
										K = -937533
										X = K + r
										K = X
										X = 0
										r = K < X
										X = d - K
									end
								end
							else
								if u < 15698025 then
									if u < 15621007 then
										if u < 15393990 then
											u = Z[a(-39686)]
											d = {}
										else
											i = nil
											N = nil
											u = Z[a(-39651)]
											x = nil
											s = nil
											A = m(A)
											d = {}
											Y = nil
											o = nil
											O = nil
											P = m(P)
											z = nil
											y = m(y)
										end
									else
										if u < 15682551 then
											f = 700214
											b = -621875
											X = F[P]
											r = a(-39621)
											g = F[A]
											c = 2579205950511
											p = 3896727297783
											U = f + p
											R = a(-39668)
											K = g(r, U)
											B = X[K]
											r = F[y]
											f = F[P]
											p = F[A]
											W = c - b
											c = -833786
											h = p(R, W)
											U = f[h]
											K = r[U]
											W = 3336216826665
											U = F[P]
											h = a(-39654)
											f = F[A]
											R = W - c
											p = f(h, R)
											R = 34345753952780
											r = U[p]
											p = a(-39684)
											W = -178918
											g = K[r]
											r = F[P]
											U = F[A]
											h = R - W
											R = 941373
											f = U(p, h)
											K = r[f]
											h = 34294213892607
											X = g[K]
											O[B] = X
											K = F[P]
											f = a(-39620)
											r = F[A]
											p = h - R
											U = r(f, p)
											g = K[U]
											r = -538801
											K = -538800
											X = O[g]
											g = K - r
											B = X < g
											u = B and 2509388 or 13570974
										else
											g = a(-39655)
											h = 20868809061190
											X = Z[g]
											K = F[P]
											f = a(-39653)
											R = -153765
											r = F[A]
											p = h - R
											U = r(f, p)
											g = K[U]
											B = X[g]
											u = B and 12236150 or 15611869
										end
									end
								else
									if u < 16638661 then
										if u < 16093928 then
											Y = nil
											B = a(-39679)
											s = a(-39658)
											d = Z[s]
											g = 17181467978935
											K = 716342
											x = F[T[2]]
											O = F[T[3]]
											X = g - K
											N = nil
											o = O(B, X)
											s = x[o]
											A = nil
											K = 30602576331649
											u = d[s]
											y = nil
											s = 0.05
											d = u(s)
											d = a(-39667)
											s = e(14590910, { z, q, T[2], T[3] })
											u = Z[d]
											d = u(s)
											B = a(-39646)
											s = a(-39658)
											g = -431149
											d = Z[s]
											x = F[T[2]]
											O = F[T[3]]
											X = g + K
											o = O(B, X)
											q = m(q)
											s = x[o]
											u = d[s]
											O = 0.15
											x = u
											s = P or O
											d = u(s)
											s = a(-39667)
											d = Z[s]
											P = nil
											x = E(4451464, { z, T[2], T[3], i })
											u = Z[a(-39643)]
											i = m(i)
											s = d(x)
											z = m(z)
											d = {}
										else
											u = Z[a(-39631)]
											d = { A }
										end
									else
										d = {}
										u = Z[a(-39639)]
									end
								end
							end
						end
					end
				end
				u = #k
				return L(d)
			end, function(Z, a)
				local L = P(a)
				local J = function(...)
					return u(Z, { ... }, a, L)
				end
				return J
			end, function(Z, a)
				local L = P(a)
				local J = function(J, T)
					return u(Z, { J, T }, a, L)
				end
				return J
			end, {}, function(Z)
				local a, u = 1, Z[1]
				while u do
					q[u], a = q[u] - 1, a + 1
					if 0 == q[u] then
						q[u], F[u] = nil, nil
					end
					u = Z[a]
				end
			end, function(Z, a)
				local L = P(a)
				local J = function(J)
					return u(Z, { J }, a, L)
				end
				return J
			end, function(Z, a)
				local L = P(a)
				local J = function()
					return u(Z, {}, a, L)
				end
				return J
			end, {}, 0, function()
				A = 1 + A
				q[A] = 1
				return A
			end, function(Z, a)
				local L = P(a)
				local J = function(J, T, k, l, d)
					return u(Z, { J, T, k, l, d }, a, L)
				end
				return J
			end, function(Z, a)
				local L = P(a)
				local J = function(J, T, k, l, d, F, q, v)
					return u(Z, { J, T, k, l, d, F, q, v }, a, L)
				end
				return J
			end
		return (z(14604222, {}))(L(d))
	end)(
		getfenv and getfenv() or _ENV,
		unpack or table[a(-39685)],
		newproxy,
		setmetatable,
		getmetatable,
		select,
		{ ... }
	)
end)(...)
